<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <InvariantGlobalization>false</InvariantGlobalization>
    <TrimMode>full</TrimMode>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)..\..\VERSION').Trim())</Version>
    <AssemblyName>Briefcase.ServerManager.App</AssemblyName>
    <RootNamespace>Briefcase.ServerManager</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Briefcase.ServerManager.Core\Briefcase.ServerManager.Core.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>
</Project>
